### ISSUE TITLE
Displaying Issue

### ISSUE THREAD

**Issue by Sera9145** [suzaku01/mhf_displayer#2]
Its only showing 4 health numbers almost at all times. If the health is above 10000 it only starts displaying correctly when it drops into the 9000 range. There are sometimes frames where it shows 5 numbers and is correct but that is very random and always removes it again after a few frames.

**Comment by suzaku01** [comment]
I got a same feedback from other, it seems the problem is size of health text.
I'll fix it later.

**Comment by rnrjsghl12** [comment]
The display mod is useful.
Would you like to add the quest elapsed time to the bottom of the number of hits?

**Comment by rnrjsghl12** [comment]
> I got a same feedback from other, it seems the problem is size of health text. I'll fix it later.

oh~ thank you so much suzaku!!

**Comment by suzaku01** [comment]
> The display mod is useful. Would you like to add the quest elapsed time to the bottom of the number of hits?

Repo updated.

**Comment by rnrjsghl12** [comment]
Please understand that I am not good at English.
I'm using the mod very well.
Is it possible to display the attack at the bottom of the retaining time? It would be very useful if you could see the value of increasing attack by various skills
<img width="192" alt="wagawegawrgwarg" src="https://user-images.githubusercontent.com/77409740/160246222-cf7f5be2-6630-46cc-907d-cef8e29af6e6.png">
.

**Comment by suzaku01** [comment]
Have never tried it but it's possible I think.
