### ISSUE TITLE
Reshade + Displayer issue

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_displayer#4]
Hey i was trying out the newest Update from MHF Displayer and apparently when reshade is installed and you try to run mhf displayer, then everything turns into a mess. 
The Resolution switches from my 1080p to something really small messing up the screen mhf displayer itself is running but the overlay is completly invisible essentially breaking it.

any idea what the issue might be or if i can fix this locally ?

**Comment by suzaku01** [comment]
I have no idea currently.
I'll take a look at it when I have time.

**Comment by suzaku01** [comment]
Mine is working fine though.
Which options are you using in reshade?

**Comment by SephVII** [comment]
> 

Which Options specificly ?

**Comment by suzaku01** [comment]
![image](https://user-images.githubusercontent.com/89909040/163652965-54bd3c3e-7eb3-48bf-a121-585142aefb48.png)
About this

**Comment by SephVII** [comment]
As you can see all is normal first.

![explorer_2022-04-16_11-21-12](https://user-images.githubusercontent.com/88888479/163669753-e6137a1e-cc08-47ec-8c06-a8c858801b9e.png)


After running MHF Display this happens and the resolution gets super small. And MHF Display is invisible and not working/Loading.

![explorer_2022-04-16_11-22-00](https://user-images.githubusercontent.com/88888479/163669804-1fd591a4-e263-4c6f-a544-dc6c57b34587.png)

Enabling and disabling reshade or mhf display doesnt change that i need to restart Frontier completly to fix this.

and here are my shaders i use currently.

![2022-04-16_11-23-21](https://user-images.githubusercontent.com/88888479/163669838-173c28c3-e71f-491b-8a75-576d2d2d5464.png)

**Comment by suzaku01** [comment]
I used the same shader options(except Clarity.fx because I couldn't find it so I used Clarity2.fx instead), but couldn't find your issue. 
What is the resolution of your monitor?

**Comment by SephVII** [comment]
> I used the same shader options(except Clarity.fx because I couldn't find it so I used Clarity2.fx instead), but couldn't find your issue. What is the resolution of your monitor?

1920 x 1080 (1080P) from the looks it seems that it reverts the resolution to the smallest one while keeping the borderless window ?

**Comment by SephVII** [comment]
> I used the same shader options(except Clarity.fx because I couldn't find it so I used Clarity2.fx instead), but couldn't find your issue. What is the resolution of your monitor?

I Found the ISSUE ! apparently when you start the MHF Displayer it uses the Fullscreen Resolution set in the Launcher Options!
![grafik](https://user-images.githubusercontent.com/88888479/163712776-c4ac9f26-d9cf-46e5-b81d-85127a3567a1.png)

If i set the fullscreen to 1080p and start mhf display it uses the correct values. Additionally i tested 1.4.1 and that one is also not invisible anymore and broken when starting with reshade apparently.
