### ISSUE TITLE
Issue i noticed in 1.4.1

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_displayer#6]
After getting Displayer working with the correct Resolution now. i noticed something when going into the Single Hunting Quest for Nono or Kamu Orugaron.
Lets say i go to the Kamu Orugaron Hunting Quest then the displayer shows the entire Quest Nono Orugaron´s HP instead of Kamu´s.
Im guessing it has something to do with the Priority  since Nono stays off screen on the quest until Kamu is dead for the last Death scene ?

Also i noticed that Smaller Monsters show Main Monster names instead of their real name.

And as Third thing i noticed is that for certain Monsters the Monster Info doesnt work correctly like it switches between 0 and other numbers back and forth. Examples are Red Lavasioth or Akura Jebia

**Comment by SephVII** [comment]
Also another note the Quest with the 2 Gougarfs only tracks Hp of one of them. No idea how it is handled in the code but they should be seperated named right ?

**Comment by suzaku01** [comment]
I confirmed both issues and am currently working it.
Thanks for feedback!
