### ISSUE TITLE
Damage Numbers cant be deactivated.

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_displayer#7]
i didnt tested 1.4.4 yet but in 1.4.3 i noticed that the on screen Damage numbers you can show dont turn off when the option is actually set to "off" they still display on the screen. 

The alternative solution i did so far was turning the Range box to the size of 1 height and 1 wide pretty much. Since setting the Size numbers to 0 apparently crashes the app.

**Comment by suzaku01** [comment]
Thanks for feedback!
